name: Bump
on:
  workflow_dispatch:
    inputs:
      version_part:
        description: 'Version part to bump'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      package:
        description: 'Target package'
        required: true
        type: string

jobs:
  bump:
    name: Bump
    uses: hexium310/workflows/.github/workflows/bump.yml@master
    with:
      version_part: ${{ github.event.inputs.version_part }}
      package: ${{ github.event.inputs.package }}
    secrets: inherit
